/* Generated By:JavaCC: Do not edit this line. ZqlJJParserConstants.java */
package anders.akita.parser;

public interface ZqlJJParserConstants {

  int EOF = 0;
  int K_ALL = 5;
  int K_AND = 6;
  int K_ANY = 7;
  int K_AS = 8;
  int K_ASC = 9;
  int K_AVG = 10;
  int K_BETWEEN = 11;
  int K_BINARY_INTEGER = 12;
  int K_BOOLEAN = 13;
  int K_BY = 14;
  int K_CASE = 15;
  int K_CHAR = 16;
  int K_COMMENT = 17;
  int K_COMMIT = 18;
  int K_CONNECT = 19;
  int K_COUNT = 20;
  int K_DATE = 21;
  int K_DAY = 22;
  int K_DELETE = 23;
  int K_DESC = 24;
  int K_DISTINCT = 25;
  int K_DIV = 26;
  int K_ELSE = 27;
  int K_END = 28;
  int K_EXCLUSIVE = 29;
  int K_EXISTS = 30;
  int K_EXIT = 31;
  int K_FLOAT = 32;
  int K_FOR = 33;
  int K_FROM = 34;
  int K_GROUP = 35;
  int K_HAVING = 36;
  int K_HOUR = 37;
  int K_IN = 38;
  int K_INSERT = 39;
  int K_INTEGER = 40;
  int K_INTERSECT = 41;
  int K_INTERVAL = 42;
  int K_INTO = 43;
  int K_IS = 44;
  int K_JOIN = 45;
  int K_LEFT = 46;
  int K_LIKE = 47;
  int K_LOCK = 48;
  int K_MAX = 49;
  int K_MIN = 50;
  int K_MOD = 51;
  int K_MINUS = 52;
  int K_MINUTE = 53;
  int K_MODE = 54;
  int K_MONTH = 55;
  int K_NATURAL = 56;
  int K_NOT = 57;
  int K_NOWAIT = 58;
  int K_NULL = 59;
  int K_NUMBER = 60;
  int K_OF = 61;
  int K_ON = 62;
  int K_ONLY = 63;
  int K_OR = 64;
  int K_ORDER = 65;
  int K_OUTER = 66;
  int K_PRIOR = 67;
  int K_QUARTER = 68;
  int K_QUIT = 69;
  int K_READ = 70;
  int K_REAL = 71;
  int K_REGEXP = 72;
  int K_ROLLBACK = 73;
  int K_ROW = 74;
  int K_SECOND = 75;
  int K_SELECT = 76;
  int K_SET = 77;
  int K_SHARE = 78;
  int K_SMALLINT = 79;
  int K_START = 80;
  int K_SUM = 81;
  int K_TABLE = 82;
  int K_THEN = 83;
  int K_TRANSACTION = 84;
  int K_UNION = 85;
  int K_UPDATE = 86;
  int K_VALUES = 87;
  int K_VARCHAR2 = 88;
  int K_VARCHAR = 89;
  int K_WEEK = 90;
  int K_WHEN = 91;
  int K_WHERE = 92;
  int K_WITH = 93;
  int K_WORK = 94;
  int K_WRITE = 95;
  int K_YEAR = 96;
  int S_NUMBER = 97;
  int FLOAT = 98;
  int INTEGER = 99;
  int DIGIT = 100;
  int LINE_COMMENT = 101;
  int MULTI_LINE_COMMENT = 102;
  int S_IDENTIFIER = 103;
  int LETTER = 104;
  int SPECIAL_CHARS = 105;
  int S_CHAR_LITERAL = 106;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"AVG\"",
    "\"BETWEEN\"",
    "\"BINARY_INTEGER\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CASE\"",
    "\"CHAR\"",
    "\"COMMENT\"",
    "\"COMMIT\"",
    "\"CONNECT\"",
    "\"COUNT\"",
    "\"DATE\"",
    "\"DAY\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"DIV\"",
    "\"ELSE\"",
    "\"END\"",
    "\"EXCLUSIVE\"",
    "\"EXISTS\"",
    "\"EXIT\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"HOUR\"",
    "\"IN\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"IS\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LOCK\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"MOD\"",
    "\"MINUS\"",
    "\"MINUTE\"",
    "\"MODE\"",
    "\"MONTH\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"NOWAIT\"",
    "\"NULL\"",
    "\"NUMBER\"",
    "\"OF\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"PRIOR\"",
    "\"QUARTER\"",
    "\"QUIT\"",
    "\"READ\"",
    "\"REAL\"",
    "\"REGEXP\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"SECOND\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SHARE\"",
    "\"SMALLINT\"",
    "\"START\"",
    "\"SUM\"",
    "\"TABLE\"",
    "\"THEN\"",
    "\"TRANSACTION\"",
    "\"UNION\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"WRITE\"",
    "\"YEAR\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "\"_\"",
    "<S_CHAR_LITERAL>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\".\"",
    "\"!=\"",
    "\"<=>\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".*\"",
    "\"||\"",
    "\"&&\"",
    "\"?\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"!\"",
  };

}
